In [24]:
import pandas as pd
import numpy as np

In [3]:
vacinations_df = pd.read_csv("country_vaccinations_raw.csv")
cases_deaths_df = pd.read_csv("worldometer_coronavirus_daily_data_raw.csv")

In [4]:
vacinations_df

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Albania,ALB,2021-01-10,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
1,Albania,ALB,2021-01-11,NaN,NaN,NaN,NaN,64.0,NaN,NaN,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
2,Albania,ALB,2021-01-12,128.0,128.0,NaN,NaN,64.0,0.00,0.00,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
3,Albania,ALB,2021-01-13,188.0,188.0,NaN,60.0,63.0,0.01,0.01,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
4,Albania,ALB,2021-01-14,266.0,266.0,NaN,78.0,66.0,0.01,0.01,NaN,23.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4430,Zimbabwe,ZWE,2021-02-23,4041.0,4041.0,NaN,2727.0,808.0,0.03,0.03,NaN,54.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1365740267...
4431,Zimbabwe,ZWE,2021-02-24,7872.0,7872.0,NaN,3831.0,1312.0,0.05,0.05,NaN,88.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1365740267...
4432,Zimbabwe,ZWE,2021-02-25,11007.0,11007.0,NaN,3135.0,1572.0,0.07,0.07,NaN,106.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1365740267...
4433,Zimbabwe,ZWE,2021-02-26,12579.0,12579.0,NaN,1572.0,1750.0,0.08,0.08,NaN,118.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1365740267...
4434,Zimbabwe,ZWE,2021-02-27,15705.0,15705.0,NaN,3126.0,2150.0,0.11,0.11,NaN,145.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1365740267...

In [15]:
cleaned_vacinations_df = vacinations_df.drop(["iso_code", "source_name", "source_website", "daily_vaccinations_per_million", "people_fully_vaccinated_per_hundred", "people_vaccinated_per_hundred", "total_vaccinations_per_hundred"], axis=1)

In [16]:
cleaned_vacinations_df

,country,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,vaccines
0,Albania,2021-01-10,0.0,0.0,NaN,NaN,NaN,Pfizer/BioNTech
1,Albania,2021-01-11,NaN,NaN,NaN,NaN,64.0,Pfizer/BioNTech
2,Albania,2021-01-12,128.0,128.0,NaN,NaN,64.0,Pfizer/BioNTech
3,Albania,2021-01-13,188.0,188.0,NaN,60.0,63.0,Pfizer/BioNTech
4,Albania,2021-01-14,266.0,266.0,NaN,78.0,66.0,Pfizer/BioNTech
...,...,...,...,...,...,...,...,...
4430,Zimbabwe,2021-02-23,4041.0,4041.0,NaN,2727.0,808.0,Sinopharm/Beijing
4431,Zimbabwe,2021-02-24,7872.0,7872.0,NaN,3831.0,1312.0,Sinopharm/Beijing
4432,Zimbabwe,2021-02-25,11007.0,11007.0,NaN,3135.0,1572.0,Sinopharm/Beijing
4433,Zimbabwe,2021-02-26,12579.0,12579.0,NaN,1572.0,1750.0,Sinopharm/Beijing
4434,Zimbabwe,2021-02-27,15705.0,15705.0,NaN,3126.0,2150.0,Sinopharm/Beijing

In [17]:
cases_deaths_df

,date,country,cumulative_total_cases,daily_new_cases,active_cases,cumulative_total_deaths,daily_new_deaths
0,2020-2-15,Afghanistan,0.0,NaN,0.0,0.0,NaN
1,2020-2-16,Afghanistan,0.0,NaN,0.0,0.0,NaN
2,2020-2-17,Afghanistan,0.0,NaN,0.0,0.0,NaN
3,2020-2-18,Afghanistan,0.0,NaN,0.0,0.0,NaN
4,2020-2-19,Afghanistan,0.0,NaN,0.0,0.0,NaN
...,...,...,...,...,...,...,...
82801,2021-2-22,Zimbabwe,35862.0,66.0,2205.0,1441.0,5.0
82802,2021-2-23,Zimbabwe,35910.0,48.0,2174.0,1448.0,7.0
82803,2021-2-24,Zimbabwe,35960.0,50.0,2094.0,1456.0,8.0
82804,2021-2-25,Zimbabwe,35994.0,34.0,2081.0,1458.0,2.0
82805,2021-2-26,Zimbabwe,36044.0,50.0,2042.0,1463.0,5.0

In [18]:
cleaned_cases_deaths_df = cases_deaths_df[cases_deaths_df["date"] > "2021-1-01"]

In [19]:
cleaned_cases_deaths_df

,date,country,cumulative_total_cases,daily_new_cases,active_cases,cumulative_total_deaths,daily_new_deaths
322,2021-1-02,Afghanistan,52709.0,123.0,8197.0,2221.0,10.0
323,2021-1-03,Afghanistan,52909.0,200.0,8274.0,2230.0,9.0
324,2021-1-04,Afghanistan,53011.0,102.0,8244.0,2237.0,7.0
325,2021-1-05,Afghanistan,53105.0,94.0,8195.0,2244.0,7.0
326,2021-1-06,Afghanistan,53207.0,102.0,8114.0,2253.0,9.0
...,...,...,...,...,...,...,...
82801,2021-2-22,Zimbabwe,35862.0,66.0,2205.0,1441.0,5.0
82802,2021-2-23,Zimbabwe,35910.0,48.0,2174.0,1448.0,7.0
82803,2021-2-24,Zimbabwe,35960.0,50.0,2094.0,1456.0,8.0
82804,2021-2-25,Zimbabwe,35994.0,34.0,2081.0,1458.0,2.0
82805,2021-2-26,Zimbabwe,36044.0,50.0,2042.0,1463.0,5.0

In [22]:
combined_df = pd.merge(cleaned_vacinations_df, cleaned_cases_deaths_df, how='inner', on="country")

In [23]:
combined_df

,country,date_x,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,vaccines,date_y,cumulative_total_cases,daily_new_cases,active_cases,cumulative_total_deaths,daily_new_deaths
0,Albania,2021-01-10,0.0,0.0,NaN,NaN,NaN,Pfizer/BioNTech,2021-1-02,58991.0,268.0,23448.0,1190.0,4.0
1,Albania,2021-01-10,0.0,0.0,NaN,NaN,NaN,Pfizer/BioNTech,2021-1-03,59438.0,447.0,23597.0,1193.0,3.0
2,Albania,2021-01-10,0.0,0.0,NaN,NaN,NaN,Pfizer/BioNTech,2021-1-04,59623.0,185.0,23428.0,1199.0,6.0
3,Albania,2021-01-10,0.0,0.0,NaN,NaN,NaN,Pfizer/BioNTech,2021-1-05,60283.0,660.0,23522.0,1210.0,11.0
4,Albania,2021-01-10,0.0,0.0,NaN,NaN,NaN,Pfizer/BioNTech,2021-1-06,61008.0,725.0,23689.0,1217.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210331,Zimbabwe,2021-02-27,15705.0,15705.0,NaN,3126.0,2150.0,Sinopharm/Beijing,2021-2-22,35862.0,66.0,2205.0,1441.0,5.0
210332,Zimbabwe,2021-02-27,15705.0,15705.0,NaN,3126.0,2150.0,Sinopharm/Beijing,2021-2-23,35910.0,48.0,2174.0,1448.0,7.0
210333,Zimbabwe,2021-02-27,15705.0,15705.0,NaN,3126.0,2150.0,Sinopharm/Beijing,2021-2-24,35960.0,50.0,2094.0,1456.0,8.0
210334,Zimbabwe,2021-02-27,15705.0,15705.0,NaN,3126.0,2150.0,Sinopharm/Beijing,2021-2-25,35994.0,34.0,2081.0,1458.0,2.0
210335,Zimbabwe,2021-02-27,15705.0,15705.0,NaN,3126.0,2150.0,Sinopharm/Beijing,2021-2-26,36044.0,50.0,2042.0,1463.0,5.0